language: node_js
node_js:
  - "0.12"
before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower update
script: gulp
notifications:
  email:
    on_success: never
    on_failure: never
